targets:
  $default:
    builders:
      drift:
        enabled: true
        generate_for:
          include:
            - lib/core/database/**/*.dart
          exclude:
            - lib/core/database/**/*.g.dart
            - lib/**/*_test.dart
            - lib/core/gen/**/*.dart
        options:
          store_date_time_values_as_text: false

      go_router_builder:
        enabled: true
        generate_for:
          include:
            - lib/core/router/**/*.dart
            - lib/features/**/router/**/*.dart
          exclude:
            - lib/core/router/**/*.g.dart
            - lib/**/*_test.dart
            

      theme_tailor_generator:
        enabled: true
        generate_for:
          include:
            - package/uikit/lib/**/*.dart
          exclude:
            - package/uikit/lib/**/*.tailor.dart
            - package/uikit/**/*_test.dart
            

      json_serializable:
        enabled: true
        generate_for:
          include:
            - lib/**/*.dart
          exclude:
            - lib/**/*.g.dart
            - lib/**/*_test.dart
            - lib/core/gen/**/*.dart
            - lib/core/database/**/*.dart
            - lib/core/router/**/*.dart
        options:
          any_map: false
          checked: false 
          create_factory: true
          create_to_json: true
          explicit_to_json: true
          include_if_null: false 
          field_rename: none
          
    sources:
      exclude:

        - "**/*.g.dart"
        - "**/*.tailor.dart"
        - "**/*.freezed.dart"
        

        - "**/*_test.dart"
        - "**/*_test_*.dart"
        - "**/test/**"
        - "**/tests/**"
        

        - "**/example/**"
        - "**/examples/**"
        - "**/.docs/**"
        

        - "**/build/**"
        - "**/.dart_tool/**"
        - "**/coverage/**"

        - "**/node_modules/**"
        - "**/.pub/**"
        - "**/.packages"

        - "**/.git/**"
        - "**/.idea/**"
        - "**/.vscode/**"
        - "**/*.iml"
        
        - "**/ios/**"
        - "**/android/**"
        - "**/web/**"
        - "**/linux/**"
        - "**/macos/**"
        - "**/windows/**"

        - "**/assets/**"
        - "**/fonts/**"


  production:
    builders:
      json_serializable:
        options:
          any_map: false
          checked: false
          explicit_to_json: true
          include_if_null: false
          ignore_unannotated: true

global_options:
  '*':
    enabled: true
    
  # JSON оптимизация
  'json_serializable|json_serializable':
    options:
      checked: false
      explicit_to_json: true